/**
 * Interoperability tests — verify Node.js implementation matches
 * Python RNS reference implementation byte-for-byte.
 *
 * Uses test vectors generated by scripts/generate-test-vectors.py
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

import { Identity } from '../src/Identity.js';
import { Destination } from '../src/Destination.js';
import { truncatedHash, sha256Hash, ed25519Verify, ed25519Sign } from '../src/utils/crypto.js';
import { fromHex, toHex, fromUtf8, equal, concat } from '../src/utils/bytes.js';
import {
  DEST_SINGLE, DEST_PLAIN, DEST_IN,
  IDENTITY_HASH_LENGTH, IDENTITY_NAME_HASH_LENGTH,
} from '../src/constants.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

let vectors;

beforeAll(() => {
  const raw = readFileSync(join(__dirname, 'vectors.json'), 'utf-8');
  vectors = JSON.parse(raw);
});

describe('Python interop: Identity', () => {
  it('computes the same identity hash from public key', () => {
    const pubKey = fromHex(vectors.identity.public_key_hex);
    expect(pubKey).toHaveLength(64);

    const identity = Identity.fromPublicKey(pubKey);
    expect(toHex(identity.hash)).toBe(vectors.identity.hash_hex);
    expect(identity.hexHash).toBe(vectors.identity.hexhash);
  });

  it('identity hash is SHA-256(public_key)[:16]', () => {
    const pubKey = fromHex(vectors.identity.public_key_hex);
    const expected = truncatedHash(pubKey, IDENTITY_HASH_LENGTH);
    expect(toHex(expected)).toBe(vectors.identity.hash_hex);
  });

  it('public key is 64 bytes, private key is 64 bytes', () => {
    expect(vectors.identity.public_key_length).toBe(64);
    expect(vectors.identity.private_key_length).toBe(64);
  });
});

describe('Python interop: Destination hashes', () => {
  let identity;

  beforeAll(() => {
    const pubKey = fromHex(vectors.destinations.identity_public_key_hex);
    identity = Identity.fromPublicKey(pubKey);

    // Verify identity hash matches
    expect(toHex(identity.hash)).toBe(vectors.destinations.identity_hash_hex);
  });

  for (let i = 0; i < 6; i++) {
    it(`matches destination hash for case ${i}`, () => {
      const tc = vectors.destinations.cases[i];

      if (tc.type === 'PLAIN') {
        // PLAIN destination — no identity
        const dest = new Destination(null, DEST_IN, DEST_PLAIN, tc.app_name, ...tc.aspects);
        expect(toHex(dest.nameHash)).toBe(tc.name_hash_hex);
        expect(dest.nameHash).toHaveLength(tc.name_hash_length);
        expect(toHex(dest.hash)).toBe(tc.destination_hash_hex);
        expect(dest.hash).toHaveLength(tc.destination_hash_length);
      } else {
        // SINGLE destination with identity
        const dest = new Destination(identity, DEST_IN, DEST_SINGLE, tc.app_name, ...tc.aspects);

        // Verify name hash
        expect(toHex(dest.nameHash)).toBe(tc.name_hash_hex);
        expect(dest.nameHash).toHaveLength(tc.name_hash_length);

        // Verify destination hash
        expect(toHex(dest.hash)).toBe(tc.destination_hash_hex);
        expect(dest.hash).toHaveLength(tc.destination_hash_length);
      }
    });
  }

  it('name hash is SHA-256(name_without_identity)[:10]', () => {
    // Manually verify one case
    const tc = vectors.destinations.cases[0]; // test_app.service
    const nameString = [tc.app_name, ...tc.aspects].join('.');
    const expected = truncatedHash(fromUtf8(nameString), IDENTITY_NAME_HASH_LENGTH);
    expect(toHex(expected)).toBe(tc.name_hash_hex);
  });

  it('destination hash is SHA-256(name_hash + identity_hash)[:16]', () => {
    const tc = vectors.destinations.cases[0];
    const nameHash = fromHex(tc.name_hash_hex);
    const identityHash = fromHex(tc.identity_hash_hex);
    const expected = truncatedHash(concat(nameHash, identityHash), IDENTITY_HASH_LENGTH);
    expect(toHex(expected)).toBe(tc.destination_hash_hex);
  });
});

describe('Python interop: Announce hash verification', () => {
  it('computes matching announce destination hash', () => {
    const av = vectors.announce;
    const pubKey = fromHex(av.identity_public_key_hex);
    const identity = Identity.fromPublicKey(pubKey);

    expect(toHex(identity.hash)).toBe(av.identity_hash_hex);

    const dest = new Destination(identity, DEST_IN, DEST_SINGLE, av.app_name, ...av.aspects);
    expect(toHex(dest.nameHash)).toBe(av.name_hash_hex);
    expect(toHex(dest.hash)).toBe(av.destination_hash_hex);
  });

  it('name_for_hash matches our name construction', () => {
    const av = vectors.announce;
    const name = [av.app_name, ...av.aspects].join('.');
    expect(name).toBe(av.name_for_hash);
  });
});

describe('Python interop: Signing', () => {
  it('verifies a Python-generated signature', () => {
    const sv = vectors.signing;
    const pubKey = fromHex(sv.public_key_hex);
    const identity = Identity.fromPublicKey(pubKey);
    const message = fromHex(sv.message_hex);
    const signature = fromHex(sv.signature_hex);

    expect(signature).toHaveLength(64);
    expect(identity.verify(message, signature)).toBe(true);
  });

  it('rejects a tampered message with Python signature', () => {
    const sv = vectors.signing;
    const pubKey = fromHex(sv.public_key_hex);
    const identity = Identity.fromPublicKey(pubKey);
    const message = fromHex(sv.message_hex);
    const signature = fromHex(sv.signature_hex);

    // Tamper with message
    const tampered = new Uint8Array(message);
    tampered[0] ^= 0xFF;

    expect(identity.verify(tampered, signature)).toBe(false);
  });
});

describe('Python interop: Encryption', () => {
  it('decrypts a Python-encrypted ciphertext', async () => {
    const ev = vectors.encryption;

    // Reconstruct the recipient identity from private key
    // Python stores private key as enc_prv(32) + sig_prv(32)
    const prvKeyBytes = fromHex(ev.recipient_private_key_hex);
    const pubKeyBytes = fromHex(ev.recipient_public_key_hex);

    // We need all four keys to create the identity
    const encPriv = prvKeyBytes.slice(0, 32);
    const sigPriv = prvKeyBytes.slice(32, 64);
    const encPub = pubKeyBytes.slice(0, 32);
    const sigPub = pubKeyBytes.slice(32, 64);

    const recipient = new Identity(encPriv, encPub, sigPriv, sigPub);

    // Verify identity hash matches
    expect(toHex(recipient.hash)).toBe(ev.recipient_hash_hex);

    // Decrypt the Python-generated ciphertext
    const ciphertext = fromHex(ev.ciphertext_hex);
    const plaintext = await recipient.decrypt(ciphertext);

    // Compare with expected plaintext
    const expectedPlaintext = fromHex(ev.plaintext_hex);
    expect(equal(plaintext, expectedPlaintext)).toBe(true);
  });

  it('decrypted text matches the original string', async () => {
    const ev = vectors.encryption;
    const prvKeyBytes = fromHex(ev.recipient_private_key_hex);
    const pubKeyBytes = fromHex(ev.recipient_public_key_hex);

    const recipient = new Identity(
      prvKeyBytes.slice(0, 32),
      pubKeyBytes.slice(0, 32),
      prvKeyBytes.slice(32, 64),
      pubKeyBytes.slice(32, 64)
    );

    const ciphertext = fromHex(ev.ciphertext_hex);
    const plaintext = await recipient.decrypt(ciphertext);

    // The original plaintext was "Hello from Python RNS!"
    const text = new TextDecoder().decode(plaintext);
    expect(text).toBe('Hello from Python RNS!');
  });
});
