/**
 * Config — parse RNS configuration files.
 *
 * Supports:
 * - JSON config (reticulum-node native format)
 * - INI config (Python RNS compatible, basic parser)
 *
 * Config directory resolution order:
 * 1. Explicit configDir parameter
 * 2. ~/.reticulum/ (default)
 *
 * Config structure (JSON):
 * {
 *   "reticulum": {
 *     "enable_transport": false,
 *     "share_instance": true,
 *     "shared_instance_port": 37428
 *   },
 *   "logging": {
 *     "loglevel": 4
 *   },
 *   "interfaces": [
 *     {
 *       "name": "Default TCP",
 *       "type": "TCPClientInterface",
 *       "enabled": true,
 *       "target_host": "rns.beleth.net",
 *       "target_port": 4242,
 *       "networkname": "",
 *       "passphrase": ""
 *     }
 *   ]
 * }
 */

import { log, LOG_DEBUG, LOG_INFO, LOG_WARNING } from './log.js';

const TAG = 'Config';

/**
 * Default configuration.
 */
export const DEFAULT_CONFIG = {
  reticulum: {
    enable_transport: false,
    share_instance: true,
    shared_instance_port: 37428,
    instance_control_port: 37429,
  },
  logging: {
    loglevel: 4,
  },
  interfaces: [],
};

/**
 * Generate the default INI config (matching Python's first-run default).
 * @returns {string}
 */
export function generateDefaultIniConfig() {
  return `# Reticulum configuration
# Generated by reticulum-node

[reticulum]
  enable_transport = False
  share_instance = Yes
  shared_instance_port = 37428
  instance_control_port = 37429

[logging]
  loglevel = 4

[interfaces]
  [[Default Interface]]
    type = AutoInterface
    enabled = Yes
`;
}

/**
 * Parse a JSON config file.
 * @param {string} content
 * @returns {object}
 */
export function parseJsonConfig(content) {
  const parsed = JSON.parse(content);
  return mergeWithDefaults(parsed);
}

/**
 * Parse a basic INI config file (Python ConfigObj compatible subset).
 * Handles [sections], [[subsections]], key = value, indentation.
 *
 * @param {string} content
 * @returns {object}
 */
export function parseIniConfig(content) {
  const result = { reticulum: {}, logging: {}, interfaces: [] };
  let currentSection = null;
  let currentInterface = null;

  const lines = content.split('\n');

  for (let line of lines) {
    // Strip comments
    const commentIdx = line.indexOf('#');
    if (commentIdx !== -1) line = line.slice(0, commentIdx);
    line = line.trim();
    if (!line) continue;

    // Subsection: [[Name]]
    const subMatch = line.match(/^\[\[(.+)\]\]$/);
    if (subMatch) {
      currentInterface = { name: subMatch[1].trim() };
      result.interfaces.push(currentInterface);
      continue;
    }

    // Section: [name]
    const secMatch = line.match(/^\[(.+)\]$/);
    if (secMatch) {
      currentSection = secMatch[1].trim().toLowerCase();
      currentInterface = null;
      continue;
    }

    // Key = Value
    const kvMatch = line.match(/^(\w+)\s*=\s*(.+)$/);
    if (kvMatch) {
      const key = kvMatch[1].trim();
      const rawVal = kvMatch[2].trim();
      const val = parseIniValue(rawVal);

      if (currentInterface) {
        currentInterface[key] = val;
      } else if (currentSection === 'reticulum') {
        result.reticulum[key] = val;
      } else if (currentSection === 'logging') {
        result.logging[key] = val;
      }
    }
  }

  return mergeWithDefaults(result);
}

/**
 * Parse an INI value string into a JS value.
 * @param {string} raw
 * @returns {string|number|boolean}
 */
function parseIniValue(raw) {
  const lower = raw.toLowerCase();
  if (lower === 'true' || lower === 'yes' || lower === 'on') return true;
  if (lower === 'false' || lower === 'no' || lower === 'off') return false;
  if (/^\d+$/.test(raw)) return parseInt(raw, 10);
  if (/^\d+\.\d+$/.test(raw)) return parseFloat(raw);
  return raw;
}

/**
 * Merge parsed config with defaults.
 * @param {object} config
 * @returns {object}
 */
function mergeWithDefaults(config) {
  return {
    reticulum: { ...DEFAULT_CONFIG.reticulum, ...(config.reticulum || {}) },
    logging: { ...DEFAULT_CONFIG.logging, ...(config.logging || {}) },
    interfaces: config.interfaces || [],
  };
}

/**
 * Load config from a directory. Tries config.json first, then config (INI).
 * @param {string} configDir
 * @returns {Promise<object>}
 */
export async function loadConfig(configDir) {
  const fs = await import('fs/promises');
  const path = await import('path');

  // Try JSON first
  try {
    const content = await fs.readFile(path.join(configDir, 'config.json'), 'utf-8');
    log(LOG_INFO, TAG, `Loaded JSON config from ${configDir}`);
    return parseJsonConfig(content);
  } catch (err) {
    if (err.code !== 'ENOENT') throw err;
  }

  // Try INI
  try {
    const content = await fs.readFile(path.join(configDir, 'config'), 'utf-8');
    log(LOG_INFO, TAG, `Loaded INI config from ${configDir}`);
    return parseIniConfig(content);
  } catch (err) {
    if (err.code !== 'ENOENT') throw err;
  }

  // No config found — generate default
  log(LOG_INFO, TAG, `No config found in ${configDir}, using defaults`);
  const defaultIni = generateDefaultIniConfig();
  await fs.mkdir(configDir, { recursive: true });
  await fs.writeFile(path.join(configDir, 'config'), defaultIni);
  return mergeWithDefaults({});
}

/**
 * Resolve the config directory.
 * @param {string} [explicit] — explicit path, if provided
 * @returns {Promise<string>}
 */
export async function resolveConfigDir(explicit) {
  if (explicit) return explicit;

  const os = await import('os');
  const path = await import('path');
  const fs = await import('fs/promises');

  // Check ~/.config/reticulum/ first
  const xdgPath = path.join(os.homedir(), '.config', 'reticulum');
  try {
    await fs.access(path.join(xdgPath, 'config'));
    return xdgPath;
  } catch {}

  // Default: ~/.reticulum/
  return path.join(os.homedir(), '.reticulum');
}
